
$(function () {
    $("#lamp").spritespin({
    width: 900,
    height: 480,
    frames: 25,
    image: [
    "images/mindfullamp1.png",
    "images/mindfullamp2.png",
    "images/mindfullamp3.png",
    "images/mindfullamp4.png",
    "images/mindfullamp5.png",
    "images/mindfullamp6.png",
    "images/mindfullamp7.png",
    "images/mindfullamp8.png",
    "images/mindfullamp9.png",
    "images/mindfullamp10.png",
    "images/mindfullamp11.png",
    "images/mindfullamp12.png",
    "images/mindfullamp13.png",
    "images/mindfullamp14.png",
    "images/mindfullamp15.png",
    "images/mindfullamp16.png",
    "images/mindfullamp17.png",
    "images/mindfullamp18.png",
    "images/mindfullamp19.png",
    "images/mindfullamp20.png",
    "images/mindfullamp21.png",
    "images/mindfullamp22.png",
    "images/mindfullamp23.png",
    "images/mindfullamp24.png",
    "images/mindfullamp25.png",
    ],
    animate: true,
    loop: true,
    frameTime: 240,
    fadeFrames: 80,
    fadeInTime: 0,
    fadeOutTime: 270
    });
});
